### ISSUE TITLE
Cannot register two routes matching "/login" for method "GET"

### ISSUE THREAD

**Issue by SKevo18** [SychO9/flarum-private-facade#3]
The following error happens at FF:

```
PHP Fatal error:  Uncaught FastRoute\BadRouteException: Cannot register two routes matching "/login" for method "GET" in /data/host/skeleton/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php:55
Stack trace:
#0 /data/host/skeleton/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(18): FastRoute\DataGenerator\RegexBasedAbstract->addStaticRoute()
#1 /data/host/skeleton/vendor/flarum/core/src/Http/RouteCollection.php(101): FastRoute\DataGenerator\RegexBasedAbstract->addRoute()
#2 /data/host/skeleton/vendor/flarum/core/src/Http/RouteCollection.php(118): Flarum\Http\RouteCollection->applyRoutes()
#3 /data/host/skeleton/vendor/flarum/core/src/Forum/ForumServiceProvider.php(221): Flarum\Http\RouteCollection->getRouteData()
#4 /data/host/skeleton/vendor/flarum/core/src/Forum/ForumServiceProvider.php(59): Flarum\Forum\ForumServiceProvider->setDefaultRoute()
#5 /data/host/skeleton/vendor/illuminate/container/Container.php(1265): Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#6 /data/host/skeleton/vendor/illuminate/container/Container.php(1229): Illuminate\Container\Container->fireCallbackArray()
#7 /data/host/skeleton/vendor/illuminate/container/Container.php(1215): Illuminate\Container\Container->fireAfterResolvingCallbacks()
#8 /data/host/skeleton/vendor/illuminate/container/Container.php(778): Illuminate\Container\Container->fireResolvingCallbacks()
#9 /data/host/skeleton/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#10 /data/host/skeleton/vendor/flarum/core/src/Forum/ForumServiceProvider.php(48): Illuminate\Container\Container->make()
#11 /data/host/skeleton/vendor/illuminate/container/Container.php(767): Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#12 /data/host/skeleton/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#13 /data/host/skeleton/vendor/flarum/core/src/Frontend/FrontendServiceProvider.php(177): Illuminate\Container\Container->make()
#14 /data/host/skeleton/vendor/illuminate/container/BoundMethod.php(36): Flarum\Frontend\FrontendServiceProvider->boot()
#15 /data/host/skeleton/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /data/host/skeleton/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /data/host/skeleton/vendor/illuminate/container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /data/host/skeleton/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call()
#19 /data/host/skeleton/vendor/flarum/core/src/Foundation/Application.php(290): Illuminate\Container\Container->call()
#20 /data/host/skeleton/vendor/flarum/core/src/Foundation/Application.php(273): Flarum\Foundation\Application->bootProvider()
#21 [internal function]: Flarum\Foundation\Application->Flarum\Foundation\{closure}()
#22 /data/host/skeleton/vendor/flarum/core/src/Foundation/Application.php(272): array_walk()
#23 /data/host/skeleton/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#24 /data/host/skeleton/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#25 /data/host/skeleton/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#26 /data/host/bbsic/flarum(24): Flarum\Console\Server->listen()
#27 {main}
  thrown in /data/host/skeleton/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php on line 55
```

PHP Flarum info:

```
Flarum core: 1.8.4
PHP version: 8.2.12
MySQL version: 11.1.2-MariaDB-1:11.1.2+maria~ubu2204
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+--------------------------------------+---------+--------+
| Flarum Extensions                    |         |        |
+--------------------------------------+---------+--------+
| ID                                   | Version | Commit |
+--------------------------------------+---------+--------+
| flarum-tags                          | v1.8.0  |        |
| flarum-suspend                       | v1.8.1  |        |
| flarum-mentions                      | v1.8.2  |        |
| flarum-sticky                        | v1.8.0  |        |
| afrux-forum-widgets-core             | v0.1.7  |        |
| fof-user-directory                   | 1.3.3   |        |
| fof-follow-tags                      | 1.2.2   |        |
| flarum-flags                         | v1.8.0  |        |
| flarum-markdown                      | v1.8.0  |        |
| zerosonesfun-member                  | 1.2     |        |
| zerosonesfun-direct-links            | 3.1     |        |
| the-turk-stickiest                   | 3.0.1   |        |
| the-turk-flamoji                     | 1.0.4   |        |
| sycho-profile-cover                  | v1.3.5  |        |
| sycho-move-posts                     | v0.1.7  |        |
| ramesh-dada-download-button          | v8.1.4  |        |
| migratetoflarum-canonical            | 1.0.0   |        |
| justoverclock-custom-html-widget     | 0.1.4   |        |
| ianm-html-head                       | 1.2.3   |        |
| ianm-follow-users                    | 1.4.3   |        |
| glowingblue-password-strength        | 3.1.0   |        |
| fof-user-bio                         | 1.3.1   |        |
| fof-upload                           | 1.5.3   |        |
| fof-split                            | 1.1.1   |        |
| fof-profile-image-crop               | 1.1.6   |        |
| fof-polls                            | 1.4.2   |        |
| fof-nightmode                        | 1.5.3   |        |
| fof-merge-discussions                | 1.4.1   |        |
| fof-masquerade                       | 2.1.4   |        |
| fof-links                            | 1.2.1   |        |
| fof-linguist                         | 1.1.2   |        |
| fof-impersonate                      | 1.1.1   |        |
| fof-formatting                       | 1.0.3   |        |
| fof-drafts                           | 1.2.10  |        |
| fof-disposable-emails                | 1.0.0   |        |
| fof-default-user-preferences         | 1.2.1   |        |
| fof-best-answer                      | 1.4.1   |        |
| fof-ban-ips                          | 1.1.1   |        |
| flarum-statistics                    | v1.8.0  |        |
| flarum-pusher                        | v1.8.0  |        |
| flarum-nicknames                     | v1.8.0  |        |
| flarum-lock                          | v1.8.0  |        |
| flarum-likes                         | v1.8.0  |        |
| flarum-lang-english                  | v1.8.0  |        |
| flarum-lang-chinese-simplified       | v1.3.0  |        |
| flarum-emoji                         | v1.8.0  |        |
| flarum-bbcode                        | v1.8.0  |        |
| ffans-clipboardjs                    | v1.0.0  |        |
| datlechin-scroll-buttons             | v1.1.0  |        |
| datlechin-link-preview               | v0.1.4  |        |
| datlechin-keyboard-shortcuts         | v0.1.1  |        |
| datlechin-birthdays                  | v2.0.1  |        |
| clarkwinkelmann-discussion-bookmarks | 2.0.1   |        |
| blomstra-welcome-login               | 0.1.0   |        |
| blomstra-fontawesome                 | 0.1.5   |        |
| askvortsov-rich-text                 | v2.1.7  |        |
| askvortsov-markdown-tables           | v1.2.1  |        |
| askvortsov-checklist                 | v1.3.1  |        |
| askvortsov-categories                | v3.0.9  |        |
| acpl-mobile-tab                      | 1.4.1   |        |
+--------------------------------------+---------+--------+
Base URL: https://x.flarum.cloud
Installation path: /data/host/x
Queue driver: sync
Session driver: file
Scheduler status: core.admin.dashboard.status.scheduler.never-run
Mail driver: smtp
Debug mode: off
```

Private Facade version: `v0.1.15`

**Comment by SychO9** [comment]
Can't have another extension that also adds a login route enabled. I would assume it's zerosonesfun-direct-links

**Comment by SKevo18** [comment]
Ah I see, thank you! So this is something that would have to be resolved in the other extension(?), which is now unfortunately abandoned. I will remove the latter from FreeFlarum until a replacement for it appears then.

**Comment by SychO9** [comment]
@SKevo18 there is nothing to resolve in either extensions. They just must not be enabled at the same time because they both add a /login route. Unfortunately flarum right now has no way of defining extensions that are incompatible together. Or a way to gracefully fail from this conflict.

**Comment by SKevo18** [comment]
I understand, I actually thought about this later and came into the same conclusion as you. I hope that this can somehow be looked at in the distant future :)
